sonar.organization=vws
sonar.projectKey=minvws_gfmodules-python-logging-library
sonar.projectName=gfmodules-python-logging-library

sonar.links.homepage=https://github.com/minvws/gfmodules-python-logging-library

sonar.sourceEncoding=UTF-8

sonar.python.version=3.11, 3.12, 3.13, 3.14

sonar.sources=gfmodules
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
